import type { Handshake } from '../types.js';

const HOST_REGISTRY: Record<string, string[]> = {
  'claude-code': [
    'AskUserQuestion',
    'EnterPlanMode',
    'ExitPlanMode',
    'TaskCreate',
    'TaskUpdate',
    'TaskList',
    'TaskGet',
    'Agent',
    'Skill',
    'Read',
    'Edit',
    'Write',
    'Bash',
    'Glob',
    'Grep',
    'WebFetch',
    'WebSearch',
    'TodoWrite',
    'SendMessage',
    'Monitor',
    'LSP',
    'NotebookEdit',
    'EnterWorktree',
    'ExitWorktree',
  ],
  codex: [
    'shell',
    'apply_patch',
    'update_plan',
    'web_search',
    'view_image',
    'exec_command',
    'write_stdin',
    'ToolRequestUserInput',
    'CollabAgent',
  ],
  opencode: [
    'bash',
    'read',
    'write',
    'edit',
    'apply_patch',
    'glob',
    'grep',
    'codesearch',
    'lsp',
    'webfetch',
    'websearch',
    'question',
    'todo',
    'task',
    'plan',
    'skill',
  ],
  'gemini-cli': [
    'shell',
    'read-file',
    'read-many-files',
    'write-file',
    'edit',
    'glob',
    'grep',
    'ls',
    'web-search',
    'web-fetch',
    'ask-user',
    'enter-plan-mode',
    'exit-plan-mode',
    'write-todos',
    'agent',
    'tracker-create-task',
    'tracker-update-task',
    'tracker-list-tasks',
    'tracker-get-task',
    'memory',
    'activate-skill',
    'complete-task',
  ],
  cline: [
    'execute_command',
    'read_file',
    'write_to_file',
    'edit_file',
    'apply_diff',
    'apply_patch',
    'search_files',
    'list_files',
    'codebase_search',
    'browser_action',
    'ask_followup_question',
    'attempt_completion',
    'new_task',
    'switch_mode',
    'update_todo_list',
    'WEB_SEARCH',
    'WEB_FETCH',
    'PLAN_MODE',
    'ACT_MODE',
    'USE_SUBAGENTS',
  ],
  'roo-code': [
    'execute_command',
    'read_file',
    'write_to_file',
    'edit_file',
    'apply_diff',
    'apply_patch',
    'search_replace',
    'search_files',
    'list_files',
    'codebase_search',
    'ask_followup_question',
    'attempt_completion',
    'new_task',
    'switch_mode',
    'update_todo_list',
    'access_mcp_resource',
    'skill',
  ],
  'kilo-code': [
    'execute_command',
    'read_file',
    'write_to_file',
    'edit_file',
    'fast_edit_file',
    'apply_diff',
    'apply_patch',
    'delete_file',
    'search_and_replace',
    'search_files',
    'list_files',
    'codebase_search',
    'browser_action',
    'ask_followup_question',
    'attempt_completion',
    'new_task',
    'switch_mode',
    'update_todo_list',
    'access_mcp_resource',
  ],
  cursor: [
    'codebase_search',
    'read_file',
    'edit_file',
    'run_terminal_command',
    'file_search',
    'grep_search',
    'list_dir',
  ],
  amp: ['shell', 'read', 'write', 'edit'],
};

export function resolveHost(hostName?: string, explicitTools?: string[]): Handshake {
  const name = hostName ?? 'generic';
  return {
    host: name,
    toolsAvailable: explicitTools ?? [],
  };
}

export { HOST_REGISTRY };
